TTPShop/TTPShop/Areas/Admin/Controllers/DanhMucsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TTPShop.Models;

namespace TTPShop.Areas.Admin.Controllers
{
    public class DanhMucsController : BaseController
    {
        private TTPShopDB db = new TTPShopDB();

        //TRANG CHỦ CỦA TRANG QUẢN LÝ DANH MỤC
        public ActionResult Index(string searchString, string currenFilter, int? page)
        {
            int pageSize = 0;
            int pageNumber = 0;
            //KIỂM TRA XEM CÓ TÌM KIẾM THEO TÊN DANH MỤC HAY KHÔNG
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currenFilter;
            }
            ViewBag.CurrentFilter = searchString;
            try
            {
                var danhMucs = db.DanhMucs.Select(t => t);
                if (!String.IsNullOrEmpty(searchString))
                {
                    danhMucs = danhMucs.Where(t => t.TenDM.Contains(searchString));
                    pageSize = danhMucs.ToList().Count;
                    if (pageSize == 0)
                    {
                        pageSize = 1;
                    }
                    //PHÂN TRANG BẰNG 1 NẾU CÓ TÌM KIẾM
                    pageNumber = (page ?? 1);
                    danhMucs = danhMucs.OrderBy(dh => dh.TenDM);
                    return View(danhMucs.ToPagedList(pageNumber, pageSize));
                }
                danhMucs = danhMucs.OrderBy(dh => dh.TenDM);
                //PHÂN TRANG BẰNG 5
                pageSize = 5;
                pageNumber = (page ?? 1);
                return View(danhMucs.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
        }

        //CHI TIẾT DANH MỤC
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            DanhMuc danhMuc = new DanhMuc();
            try
            {
                danhMuc = db.DanhMucs.Find(id);
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
                
            if (danhMuc == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(danhMuc);
        }

        //TẠO DNAH MỤC
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDM,TenDM,AnhDM")] DanhMuc danhMuc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(danhMuc.TenDM))
                    {
                        ViewBag.Error = "Vui lòng nhập tên danh mục!";
                        return View(danhMuc);
                    }
                    danhMuc.AnhDM = "";
                    var f = Request.Files["ImageFile"];

                    if (f != null && f.ContentLength > 0)
                    {
                        //LẤY FILE ẢNH VÀ LƯU VÀO THƯ MỤC TRONG PROJECT
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/Areas/Admin/Assets/images/" + FileName);
                        f.SaveAs(UploadPath);
                        danhMuc.AnhDM = FileName;
                    }
                    else
                    {
                        string FileName = "";
                        danhMuc.AnhDM = FileName;
                    }
                    db.DanhMucs.Add(danhMuc);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(danhMuc);
                }
                
            }
            catch (Exception e)
            {
                ViewBag.Error = "Lỗi thêm: " + e.Message;
                return View(danhMuc);
            }
        }

        //CHỈNH SỬA
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            DanhMuc danhMuc = new DanhMuc();
            try
            {
                danhMuc = db.DanhMucs.Find(id);
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
                
            if (danhMuc == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(danhMuc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDM,TenDM,AnhDM")] DanhMuc danhMuc)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(danhMuc.TenDM))
                    {
                        ViewBag.Error = "Vui lòng nhập tên danh mục!";
                        return View(danhMuc);
                    }
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        //LẤY FILE ẢNH VÀ LƯU VÀO THƯ MỤC TRONG PROJECT
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/Areas/Admin/Assets/images/" + FileName);
                        f.SaveAs(UploadPath);
                        danhMuc.AnhDM = FileName;
                    }
                    else
                    {
                        danhMuc.AnhDM = Request["oldImage"];
                    }
                    db.Entry(danhMuc).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(danhMuc);
                }
                
            }
            catch (Exception e)
            {
                ViewBag.Error = "Lỗi: " + e.Message;
                return View(danhMuc);
            }
        }

        //XÓA DANH MỤC
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            DanhMuc danhMuc = new DanhMuc();
            try
            {
                danhMuc = db.DanhMucs.Find(id);
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
            if (danhMuc == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhMuc danhMuc = new DanhMuc();
            try
            {
                danhMuc = db.DanhMucs.Find(id);
                if(danhMuc == null)
                {
                    return RedirectToAction("Index");
                }
                db.DanhMucs.Remove(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                ViewData["Error"] = "Danh mục liên kết với các mục khác vui lòng xóa chúng trước khi xóa danh mục này!";
                return View(danhMuc);
            }
            
        }

        //GIẢI PHÓNG CÁC TÀI NGUYÊN KHÔNG CẦN THIẾT
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TTPShop/TTPShop/Areas/Admin/Controllers/LienHesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TTPShop.Models;

namespace TTPShop.Areas.Admin.Controllers
{
    public class LienHesController : BaseController
    {
        private TTPShopDB db = new TTPShopDB();

        //TRANG CHỦ LIÊN HỆ
        public ActionResult Index()
        {
            List<LienHe> lienHes = new List<LienHe>();
            try
            {
                lienHes = db.LienHes.ToList();
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
            return View(lienHes);
        }

        //CHI TIẾT
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }

            LienHe lienHe = new LienHe();
            try
            {
                lienHe = db.LienHes.Find(id);
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
                
            if (lienHe == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(lienHe);
        }

        //THÊM
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLH,DiaChi,Email,DienThoai,ThoiGianLamViec")] LienHe lienHe)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string error = ValidLienHe(lienHe);
                    if(error.Length > 0)
                    {
                        ViewBag.Error = error;
                        return View(lienHe);
                    }
                    db.LienHes.Add(lienHe);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(lienHe);
                }
                
            }
            catch (Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
        }

        //HÀM KIỂM TRA TÍNH HỢP LỆ DỮ LIỆU
        public string ValidLienHe(LienHe lienHe)
        {
            if (string.IsNullOrEmpty(lienHe.DiaChi))
            {
                return "Vui lòng nhập địa chỉ!";
            }
            if (string.IsNullOrEmpty(lienHe.Email))
            {
                return "Vui lòng nhập email!";
            }
            if (string.IsNullOrEmpty(lienHe.DienThoai))
            {
                return "Vui lòng nhập số điện thoại!";
            }
            if (string.IsNullOrEmpty(lienHe.ThoiGianLamViec))
            {
                return "Vui lòng nhập thời gian làm việc!";
            }

            string expression = "\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
            if (!Regex.IsMatch(lienHe.Email, expression))
            {
                return "Email chưa đúng định dạng!";
            }
            string regex = @"^([\+]?61[-]?|[0])?[1-9][0-9]{8}$";

            if (!Regex.IsMatch(lienHe.DienThoai, regex))
            {
                return "Số điện thoại không hợp lệ!";
            }
            return "";
        }

        //CHỈNH SỬA
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            LienHe lienHe = new LienHe();
            try
            {
                lienHe = db.LienHes.Find(id);
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
            
            if (lienHe == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(lienHe);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLH,DiaChi,Email,DienThoai,ThoiGianLamViec")] LienHe lienHe)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string error = ValidLienHe(lienHe);
                    if(error.Length > 0)
                    {
                        ViewBag.Error = error;
                        return View(lienHe);
                    }
                    db.Entry(lienHe).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(lienHe);
                }
                
            }
            catch (Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
        }

        //XÓA
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            LienHe lienHe = new LienHe();
            try
            {
                lienHe = db.LienHes.Find(id);
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
                
            if (lienHe == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(lienHe);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LienHe lienHe = new LienHe();
            try
            {
                lienHe = db.LienHes.Find(id);
                if(lienHe == null)
                {
                    return RedirectToAction("Index");
                }
                db.LienHes.Remove(lienHe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TTPShop/TTPShop/Areas/Admin/Views/Shared/_FooterAdmin.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-left">
            </div>
            <div class="col-6 text-right">
                <p>
                    Copyright TTP SHOP &copy;
                    <script>document.write(new Date().getFullYear());</script>
                </p>
            </div>
        </div>
    </div>
</footer>

TTPShop/TTPShop/Areas/Admin/Views/Shared/_HeaderAdmin.cshtml
<nav class="navbar navbar-expand navbar-light bg-white">
    <a class="sidebar-toggle d-flex mr-2">
        <i class="hamburger align-self-center"></i>
    </a>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="dashboard-default.html#" data-toggle="dropdown">
                    <i class="align-middle" data-feather="settings"></i>
                </a>

                <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="dashboard-default.html#" data-toggle="dropdown">
                    <span class="text-dark">@Session["HoTen"]</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="/">Về trang chủ</a>
                    <a class="dropdown-item" href="@Url.Action("Logout","Home")">Đăng xuất</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

TTPShop/TTPShop/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
    <meta name="author" content="Bootlab">

    <title>TTP Shop</title>

    <link rel="shortcut icon" href="~/Areas/Admin/Assets/img/logo.jpg" type="image/x-icon" />

    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>

    <link href="~/Areas/Admin/Assets/css/classic.css" rel="stylesheet">
    <link href="~/Areas/Admin/Assets/css/style.css" rel="stylesheet">

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120946860-6"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-120946860-6');</script>
    <script>
        (function (h, o, t, j, a, r) {
            h.hj = h.hj || function () { (h.hj.q = h.hj.q || []).push(arguments) };
            h._hjSettings = { hjid: 1685936, hjsv: 6 };
            a = o.getElementsByTagName('head')[0];
            r = o.createElement('script'); r.async = 1;
            r.src = t + h._hjSettings.hjid + j + h._hjSettings.hjsv;
            a.appendChild(r);
        })(window, document, 'https://static.hotjar.com/c/hotjar-', '.js?sv=');</script>
</head>

<body>
    <div class="wrapper">
        @{
            Html.RenderPartial("_SidebarAdmin");
        }

        <div class="main">
            @{ Html.RenderPartial("_HeaderAdmin"); }

            <main class="content">
                @RenderBody()
            </main>

            @{ Html.RenderPartial("_FooterAdmin"); }
        </div>
    </div>

    <script src="~/Areas/Admin/Assets/js/app.js"></script>
    <script src="~/Areas/Admin/Assets/js/setting.js"></script>

</body>
</html>

TTPShop/TTPShop/Areas/Admin/Views/Shared/_SidebarAdmin.cshtml
<nav id="sidebar" class="sidebar">
    <div class="sidebar-content ">
        <a class="sidebar-brand" href="@Url.Action("Index", "Home")">
            <i class="align-middle" data-feather="box"></i>
            <span class="align-middle">Quản lý</span>
        </a>

        <ul class="sidebar-nav">
            <li class="sidebar-header">
                Quản trị
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "DanhMucs")" class="sidebar-link @(ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")">
                    <i class="align-middle bx bx-list-ul"></i> <span class="align-middle">Danh mục</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "SanPhams")" class="sidebar-link">
                    <i class="align-middle bx bx-store"></i> <span class="align-middle">Sản phẩm</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "TaiKhoans")" class="sidebar-link">
                    <i class="align-middle bx bx-user"></i> <span class="align-middle">Tài khoản</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "LienHes")" class="sidebar-link">
                    <i class="align-middle bx bxs-contact"></i> <span class="align-middle">Liên hệ</span>
                </a>
            </li>
            <li class="sidebar-item">
                <a href="@Url.Action("Index", "DonHangs")" class="sidebar-link">
                    <i class="align-middle bx bx-receipt"></i> <span class="align-middle">Đơn hàng</span>
                </a>
            </li>

        </ul>
    </div>
</nav>