TTPShop/TTPShop/Models/SanPham.cs
namespace TTPShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            Carts = new HashSet<Cart>();
            ChiTietDHs = new HashSet<ChiTietDH>();
        }

        [Key]
        public int MaSP { get; set; }

        public int MaDM { get; set; }

        [Required(ErrorMessage ="Vui lòng nhập tên sản phẩm!")]
        [StringLength(100)]
        public string TenSP { get; set; }
        [Required(ErrorMessage ="Vui lòng nhập giá bán!")]
        public int GiaBan { get; set; }

        [StringLength(100)]
        public string AnhSP { get; set; }

        public string MoTa { get; set; }

        public int? PhanTramKM { get; set; }

        public DateTime NgayTao { get; set; }

        public int? SoLuong { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDH> ChiTietDHs { get; set; }

        public virtual DanhMuc DanhMuc { get; set; }

        public virtual DanhMuc DanhMuc1 { get; set; }
    }
}

TTPShop/TTPShop/Areas/Admin/Controllers/SanPhamsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TTPShop.Models;

namespace TTPShop.Areas.Admin.Controllers
{
    public class SanPhamsController : BaseController
    {
        private TTPShopDB db = new TTPShopDB();

        //TRANG CHỦ TRANG SẢN PHẨM (TÌM KIẾM THEO TÊN SP, SẮP XẾP THEO TÊN SP, TÊN DANH MỤC)
        public ActionResult Index(string sortOder, string searchString, string currenFilter, int? page)
        {
            int pageSize = 0;
            int pageNumber = 0;
            ViewBag.CurrentSort = sortOder;
            ViewBag.SapTheoTen = string.IsNullOrEmpty(sortOder) ? "name_desc" : "";
            ViewBag.SapTheoDanhMuc = sortOder == "TenDM" ? "dm_desc" : "TenDM";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currenFilter;
            }
            ViewBag.CurrentFilter = searchString;
            try
            {
                var sanPhams = db.SanPhams.Select(t => t);
                if (!String.IsNullOrEmpty(searchString))
                {
                    sanPhams = sanPhams.Where(t => t.TenSP.Contains(searchString));
                }
                switch (sortOder)
                {
                    case "name_desc":
                        sanPhams = sanPhams.OrderByDescending(t => t.TenSP);
                        break;

                    case "TenDM":
                        sanPhams = sanPhams.OrderBy(t => t.DanhMuc.TenDM);
                        break;

                    case "dm_desc":
                        sanPhams = sanPhams.OrderByDescending(t => t.DanhMuc.TenDM);
                        break;

                    default:
                        sanPhams = sanPhams.OrderBy(t => t.TenSP);
                        break;
                }

                if (!String.IsNullOrEmpty(searchString))
                {
                    pageSize = sanPhams.ToList().Count;
                    if (pageSize == 0)
                    {
                        pageSize = 1;
                    }
                    pageNumber = (page ?? 1);
                    return View(sanPhams.ToPagedList(pageNumber, pageSize));
                }
                pageSize = 5;
                pageNumber = (page ?? 1);
                return View(sanPhams.ToPagedList(pageNumber, pageSize));
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }  
        }

        //CHI TIẾT SẢN PHẨM
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            SanPham sanPham = new SanPham();
            try
            {
                sanPham = db.SanPhams.Find(id);
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            } 
            if (sanPham == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(sanPham);
        }

        //THÊM SẢN PHẨM
        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Create([Bind(Include = "MaSP,MaDM,TenSP,GiaBan,AnhSP,MoTa,PhanTramKM,SoLuong")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    sanPham.AnhSP = "";
                    var f = Request.Files["ImageFile"];
                    if (string.IsNullOrEmpty(sanPham.MoTa))
                    {
                        sanPham.MoTa = "";
                    }
                    if (sanPham.SoLuong == null)
                    {
                        sanPham.SoLuong = 0;
                    }
                    if (sanPham.PhanTramKM == null)
                    {
                        sanPham.PhanTramKM = 0;
                    }
                    if (sanPham.SoLuong < 0 || sanPham.PhanTramKM < 0 || sanPham.GiaBan < 0 || sanPham.PhanTramKM > 100)
                    {
                        ViewBag.Error = "Giá sản phẩm, khuyến mãi, giá bán phải lớn hơn 0 và khuyến mãi nhỏ hơn 100!";
                        ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                        return View(sanPham);
                    }
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/Areas/Admin/Assets/images/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.AnhSP = FileName;
                    }
                    sanPham.NgayTao = DateTime.Now;
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                    return View(sanPham);
                }
                
            }
            catch (Exception e)
            {
                ViewBag.Error = "Lỗi thêm: " + e.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }
        }

        //CHỈNH SỬA
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            SanPham sanPham = new SanPham();
            try
            {
                sanPham = db.SanPhams.Find(id);
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
                
            if (sanPham == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);
        }

        [HttpPost]
        [ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "MaSP,MaDM,TenSP,GiaBan,AnhSP,MoTa,PhanTramKM,SoLuong,NgayTao")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (string.IsNullOrEmpty(sanPham.MoTa))
                    {
                        sanPham.MoTa = "";
                    }
                    if (sanPham.SoLuong == null)
                    {
                        sanPham.SoLuong = 0;
                    }
                    if (sanPham.PhanTramKM == null)
                    {
                        sanPham.PhanTramKM = 0;
                    }
                    if (sanPham.SoLuong < 0 || sanPham.PhanTramKM < 0 || sanPham.GiaBan < 0)
                    {
                        ViewBag.Error = "Giá sản phẩm, Khuyến mãi, giá bán phải lớn hơn 0!";
                        ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                        return View(sanPham);
                    }

                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/Areas/Admin/Assets/images/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.AnhSP = FileName;
                    }
                    else
                    {
                        sanPham.AnhSP = Request["oldImage"];
                    }
                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                    return View(sanPham);
                }
                
            }
            catch (Exception e)
            {
                ViewBag.Error = "Lỗi: " + e.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }
        }

        //XÓA
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            SanPham sanPham = new SanPham();
            try
            {
                sanPham = db.SanPhams.Find(id);
            }
            catch
            {
                return RedirectToAction("ServerError", "ErrorAdmin");
            }
            if (sanPham == null)
            {
                return RedirectToAction("NotFoundPage", "ErrorAdmin");
            }
            return View(sanPham);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = new SanPham();
            try
            {
                sanPham = db.SanPhams.Find(id);
                if (sanPham == null)
                {
                    return RedirectToAction("NotFoundPage", "ErrorAdmin");
                }
                db.SanPhams.Remove(sanPham);
                db.SaveChanges();

TTPShop/TTPShop/Areas/Admin/Views/SanPhams/Create.cshtml
@model TTPShop.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Tạo mới sản phẩm</h2>

<script src="~/Theme/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label>Danh mục</label>
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Tên sản phẩm</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Giá bán</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Ảnh sản phẩm</label>
        <div class="col-md-10">
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="~/Theme/images/no-image-news.png" />
            <p><label for="ufile" style="cursor:pointer;">Chọn file ảnh</label></p>
            <input type="file" name="ImageFile" id="ufile" style="display:none;" onchange="loadFile(event)" />
        </div>
    </div>

    <div class="form-group">
        <label>Mô tả</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Khuyến mãi</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhanTramKM, new { htmlAttributes = new { @class = "form-control", @min = 0, @max = 100 } })
            @Html.ValidationMessageFor(model => model.PhanTramKM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Số lượng</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control", @min = 0 } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (ViewBag.Error != null)
    {
        <div class="row py-1 alert alert-danger text-center">
            <p class="text-center title-error">@ViewBag.Error</p>
        </div>
    }

    <div class="py-3 pb-4 border-bottom">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-primary" />
                <a class="btn border button" href="/Admin/SanPhams">Trở lại</a>
            </div>
        </div>
    </div>
</div>
}


<script>
    var loadFile = function (event) {
        var image = document.getElementById('output')
        image.src = URL.createObjectURL(event.target.files[0])
    }
</script>

TTPShop/TTPShop/Areas/Admin/Views/SanPhams/Delete.cshtml
@model TTPShop.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    var ImagePath = "~/Areas/Admin/Assets/images/" + Model.AnhSP;
}

<h2>Xóa sản phẩm</h2>

<h3>Bạn có chắc muốn xóa?</h3>

<div class="wrapper bg-white mt-sm-5">
    <div class="py-1 row-details">
        <div class="row py-2">
            <div class="col-md-6">
                <label>Tên sản phẩm: </label> <b>@Model.TenSP</b>
            </div>
            <div class="col-md-6">
                @if (ViewData["MaDM"] != null)
                {
                    <label>Tên danh mục: </label> <b>@ViewData["MaDM"]</b>
                }
                else
                {
                    <label>Tên danh mục: </label> <b>@Model.DanhMuc.TenDM</b>
                }
            </div>
        </div>
        <div class="row py-2">
            <div class="col-md-6">
                <label>Giá bán: </label> <b>@Model.GiaBan.ToString("N0") VNĐ</b>
            </div>
            <div class="col-md-6">
                <label>Khuyến mãi: </label> <b>@Model.PhanTramKM%</b>
            </div>
        </div>
        <div class="row py-2">
            <div class="col-md-6">
                <label>Số lượng: </label> <b>@Model.SoLuong</b>
            </div>
            <div class="col-md-6">
                <label>Ngày tạo: </label> <b>@Model.NgayTao</b>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <label>Ảnh: </label>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" alt="Alternate Text" />
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <label>Mô tả: </label>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-12">
                <b>@Html.Raw(Model.MoTa)</b>
            </div>
        </div>

        @if (ViewData["Error"] != null)
        {
            <div class="row py-1 alert alert-danger text-center">
                <p class="text-center title-error">@ViewData["Error"]</p>
            </div>
        }

        <div class="py-3 pb-4 border-bottom">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Xóa" class="btn btn-danger" />
                            <a class="btn border button" href="/Admin/SanPhams">Trở lại</a>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

TTPShop/TTPShop/Areas/Admin/Views/SanPhams/Details.cshtml
@model TTPShop.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    var ImagePath = "~/Areas/Admin/Assets/images/" + Model.AnhSP;
}

<h2>Chi tiết</h2>

<div class="wrapper bg-white mt-sm-5">
    <div class="py-1 row-details">
        <div class="row py-2">
            <div class="col-md-6">
                <label>Tên sản phẩm: </label> <b>@Model.TenSP</b>
            </div>
            <div class="col-md-6">
                <label>Tên danh mục: </label> <b>@Model.DanhMuc.TenDM</b>
            </div>
        </div>
        <div class="row py-2">
            <div class="col-md-6">
                <label>Giá bán: </label> <b>@Model.GiaBan.ToString("N0") VNĐ</b>
            </div>
            <div class="col-md-6">
                <label>Khuyến mãi: </label> <b>@Model.PhanTramKM%</b>
            </div>
        </div>
        <div class="row py-2">
            <div class="col-md-6">
                <label>Số lượng: </label> <b>@Model.SoLuong</b>
            </div>
            <div class="col-md-6">
                <label>Ngày tạo: </label> <b>@Model.NgayTao</b>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <label>Ảnh: </label>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" alt="Alternate Text" />
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-6">
                <label>Mô tả: </label>
            </div>
        </div>
        <div class="row py-1">
            <div class="col-md-12">
                <b>@Html.Raw(Model.MoTa)</b>
            </div>
        </div>
        <div class="py-3 pb-4 border-bottom">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a class="btn btn-primary" href="@Url.Action("Edit", new{ id = Model.MaSP })">Sửa</a>
                    <a class="btn border button" href="/Admin/SanPhams">Trở lại</a>
                </div>
            </div>
        </div>
    </div>
</div>

TTPShop/TTPShop/Areas/Admin/Views/SanPhams/Edit.cshtml
@model TTPShop.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

    var anhSanPham = Model.AnhSP;
    var ImagePath = "~/Areas/Admin/Assets/images/" + anhSanPham;
}

<h2>Sửa sản phẩm</h2>

<script src="~/Theme/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Edit", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaSP)

    <div class="form-group">
        <label>Danh mục</label>
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Tên sản phẩm</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Giá bán</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Ảnh</label>
        <div class="col-md-10">
            <img id="output" class="img-rounded" alt="Ảnh" width="180" height="200" src="@Url.Content(ImagePath)" />
            <p><label for="ufile" style="cursor:pointer;">Chọn file ảnh</label></p>
            <input type="file" name="ImageFile" id="ufile" style="display:none;" onchange="loadFile(event)" />
            @if (Model.AnhSP != null && Model.AnhSP != "")
            {
                <input type="text" name="oldImage" style="display:none;" value="@Url.Content(anhSanPham)" />
            }
            else
            {
                <input type="text" name="oldImage" style="display:none;" value="" />
            }
        </div>
    </div>

    <div class="form-group">
        <label>Mô tả</label>
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" }, id = "moTa" })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            <script type="text/javascript">

                CKEDITOR.config.language = "vi";
                CKEDITOR.config.htmlEncodeOutput = false;
                CKEDITOR.config.pasteFormWordPromptCleanup = true;
                CKEDITOR.config.pasteFormWordRemoveFontStyles = false;
                CKEDITOR.config.pasteFormWordRemoveStyles = false;
                CKEDITOR.config.ProcessHTMLEntities = false;
                CKEDITOR.config.entities = false;
                CKEDITOR.config.entities_latin = false;
                CKEDITOR.config.ForceSimpleAmpersand = true;
                CKEDITOR.replace('moTa');

            </script>
        </div>
    </div>

    <div class="form-group">
        <label>Khuyến mãi</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhanTramKM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhanTramKM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Số lượng</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Ngày tạo</label>
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.NgayTao, new { @readonly = "readonly" })
        </div>
    </div>
    @if (ViewBag.Error != null)
    {
    <div class="row py-1 alert alert-danger text-center">
        <p class="text-center title-error">@ViewBag.Error</p>
    </div>
    }

    <div class="py-3 pb-4 border-bottom">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <a class="btn border button" href="/Admin/SanPhams">Trở lại</a>
            </div>
        </div>
    </div>
</div>
}

<script>
    var loadFile = function (event) {
        var image = document.getElementById('output')
        image.src = URL.createObjectURL(event.target.files[0])
    }
</script>

TTPShop/TTPShop/Areas/Admin/Views/SanPhams/Index.cshtml
@model PagedList.IPagedList<TTPShop.Models.SanPham>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="home-section">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2><b>Danh sách sản phẩm</b></h2></div>

                    <div class="col-sm-4">
                        <a href="@Url.Action("Create")" class="btn btn-info add-new"><i class="fa fa-plus"></i> Thêm </a>
                    </div>
                </div>
            </div>
            <table class="table table-bordered sapham-col" id="table-user">
                <thead>
                    <tr>
                        <th>
                            @Html.ActionLink("Tên danh mục", "Index", new { sortOder = ViewBag.SapTheoDanhMuc, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th>
                            @Html.ActionLink("Tên sản phẩm", "Index", new { sortOder = ViewBag.SapTheoTen, currentFilter = ViewBag.CurrentFilter })
                        </th>
                        <th class="text-center">
                            <span>Giá bán</span>
                        </th>
                        <th class="text-center">
                            <span>Ảnh</span>
                        </th>
                        <th class="text-center">
                            <span>Khuyến mãi</span>
                        </th>
                        <th class="text-center">
                            <span>Số lượng</span>
                        </th>
                        <th class="text-center">
                            <span>Thiết lập</span>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DanhMuc.TenDM)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSP)
                        </td>
                        <td>
                            @item.GiaBan.ToString("N0") VNĐ
                        </td>
                        <td>
                            @{
                                string ImagePath = "~/Areas/Admin/Assets/images/" + item.AnhSP;
                            }
                            <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" alt="Alternate Text" />
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.PhanTramKM)%
                        </td>

                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.SoLuong)
                        </td>
                        <td class="text-center align-middle">
                            <a href="@Url.Action("Details", new { id = item.MaSP })" class="edit btn btn-edit" title="Chi tiết" data-toggle="tooltip"><i class="bx bx-detail"></i></a>
                            <a href="@Url.Action("Edit", new { id = item.MaSP })" class="edit btn btn-edit" title="Sửa" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>

                            <a href="@Url.Action("Delete", new { id = item.MaSP })" data-toggle="tooltip" class="delete btn btn-link btn-delete" title="Xóa"><i class="material-icons">&#xE872;</i></a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

Trang @(Model.PageCount <Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOder = ViewBag.CurrentSort, currentFilter = ViewBag.CurentFilter }))